<?php $this->htmlElement('body')->appendAttribute('class', 'vocabs browse'); ?>
<h1>Browse Vocabularies</h1>

<a href="#" class="button">Import new vocabulary</a>

<table id="vocabs-list">
    <thead>
        <tr>
            <th>Name</th>
        </tr>
    </thead>
    <tbody>

        <?php foreach($vocabularies as $vocabulary): ?>

            <tr>
                <td>
                    <span class="record-name">
                        <a href="#"><?php echo $vocabulary->getLabel(); ?></a>
                    </span>
                </td>
            </tr>
            
        <?php endforeach; ?>
        
    </tbody>
</table>